# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core
# Add steps that run tests, create NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-lastest

variables:
  buildConfiguration: 'Release'
  
steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'donet build $(buildConfiguration)'  